### ISSUE TITLE
Kenben board setup for final capstone project

### ISSUE THREAD

**Issue by faisalakb** [Ochiengsteven/book-an-appointment-backend#33]
- Github Project link: https://github.com/users/Ochiengsteven/projects/5/views/1

- we are the group of three members:  
@faisalakb 
@newtonah0 
@Ochiengsteven 

Kenben board screen shot 
![kenbenSetup](https://github.com/Ochiengsteven/book-an-appointment-backend/assets/70527740/4be5c499-9157-417a-8e6f-d7c518f73567)

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!





![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️


- [ ] Kindly, add points to this task:

![image](https://github.com/Ochiengsteven/book-an-appointment-backend/assets/57421823/4f38394b-cba5-4a64-a5db-8dd24826e9a9)

After adding the points, kindly double check that no one has more than 5 points than any other person in the team.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
please check i updated the above requirments

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
